# Generic Stuff
title: Robobenklein.Github.io
email: robobenklein@robosane.net
description: >
  Just a collection of my experiences, stuff I learned, tips, tricks, and whatnot as
  I work with various new or open source technologies.
twitter_username: robobenklein
github_username: robobenklein

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"

# Conversion
markdown:    kramdown
excerpt_separator: "\n\n"

# Github Flavor Markdown nom nom
kramdown:
  input: GFM
