# Generic Stuff
title: Robobenklein.Github.io
email: robobenklein@robosane.net
description: >
  Just a collection of my experiences, stuff I learned, tips, tricks, and whatnot as
  I work with various new or open source technologies.
twitter_username: robobenklein
github_username: robobenklein


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"

# Conversion
markdown:    kramdown
excerpt_separator: "\n\n"

# Github Flavor Markdown nom nom
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

highlighter: pygments

timezone: America/New_York
future: true

owner:
  name: Ben Klein
  avatar: RobobenkleinJustRbright256x256.png
  bio: "Owner of Robosane, Tech Enthusiast, and Linux Gamer."
  email: robobenklein@robosane.net
  twitter: robobenklein
  github: robobenklein
  stackexchange: robobenklein

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/

paginate: 5

exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
