# Generic Stuff
title: Robobenklein.Github.io
email: robobenklein@robosane.net
description: >
  Just a collection of my experiences, stuff I learned, tips, tricks, and whatnot as
  I work with various new or open source technologies.
twitter_username: robobenklein
github_username: robobenklein

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"

# Where things are
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

# Github Flavor Markdown nom nom
kramdown:
  input: GFM
